# Generated by Django 3.2 on 2021-04-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date added')),
                ('cust_email', models.CharField(max_length=200)),
                ('cust_location', models.CharField(max_length=200)),
                ('product_id', models.CharField(max_length=200)),
                ('product_quantity', models.IntegerField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date added')),
                ('cust_email', models.CharField(max_length=200)),
                ('cust_location', models.CharField(max_length=200)),
                ('product_id', models.CharField(max_length=200)),
                ('product_quantity', models.IntegerField(max_length=200)),
                ('wholesale_cost', models.IntegerField(max_length=200)),
                ('retail_cost', models.IntegerField(max_length=200)),
                ('seller_id', models.IntegerField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
