# Generated by Django 3.2 on 2021-04-10 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210410_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomingorders',
            name='product_quantity',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='product_quantity',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='retail_cost',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='seller_id',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='wholesale_cost',
        ),
    ]
